# Copyright (C) 2019 Witekio
# Released under the MIT license (see COPYING.MIT for the terms)
do_configure_append_sota() {
    # ramblk for inird
    kernel_configure_variable BLK_DEV_RAM y
    kernel_configure_variable CMA_SIZE_MBYTES 256
    kernel_configure_variable BCM_VC_SM n
    kernel_configure_variable I2C_BCM2835 y

    kernel_configure_variable DRM y
    kernel_configure_variable DRM_FBDEV_EMULATION y
    #kernel_configure_variable DRM_VC4 y
    #kernel_configure_variable COMPILE_TEST y
    #We need audio to meet depeendies for VC4 GPU 
    #kernel_configure_variable SND y
    #kernel_configure_variable SND_SOC y
    #kernel_configure_variable SND_BCM2835 y
    #kernel_configure_variable SND_BCM2835_SOC_I2S y

    kernel_configure_variable OVERLAY_FS y

    kernel_configure_variable CRYPTO_AES_ARM_BS y
    kernel_configure_variable CRYPTO_SHA1_ARM_NEON y
    kernel_configure_variable CRYPTO_USER_API_SKCIPHER y

    #Remove all unused modules

    kernel_configure_variable QRTR n
    kernel_configure_variable QRTR_SMD n
    kernel_configure_variable QCOM_EBI2 n
    kernel_configure_variable SIMPLE_PM_BUS n
    kernel_configure_variable OF_ALL_DTBS n
    kernel_configure_variable ATMEL_SSC n
    kernel_configure_variable QCOM_COINCELL n
    kernel_configure_variable SCSI_HISI_SAS n
    kernel_configure_variable FIREWIRE n
    kernel_configure_variable FW_CFG_SYSFS n
    kernel_configure_variable ALTERA_TSE n

    kernel_configure_variable BINFMT_MISC n
    kernel_configure_variable NET_KEY n
    kernel_configure_variable NET_IPIP n
    kernel_configure_variable NET_IPGRE_DEMUX n
    kernel_configure_variable NET_IPGRE n
    kernel_configure_variable INET_AH n
    kernel_configure_variable INET_ESP n
    kernel_configure_variable INET_IPCOMP n
    kernel_configure_variable INET_XFRM_MODE_TRANSPORT n
    kernel_configure_variable INET_XFRM_MODE_TUNNEL n
    kernel_configure_variable INET_XFRM_MODE_BEET n
    kernel_configure_variable INET_DIAG n
    kernel_configure_variable TCP_CONG_BBR n
    kernel_configure_variable IPV6 n
    kernel_configure_variable INET6_AH n
    kernel_configure_variable INET6_ESP n
    kernel_configure_variable INET6_IPCOMP n
    kernel_configure_variable IPV6_TUNNEL n
    kernel_configure_variable NF_CONNTRACK n
    kernel_configure_variable NF_CT_PROTO_DCCP n
    kernel_configure_variable NF_CT_PROTO_UDPLITE n
    kernel_configure_variable NF_CONNTRACK_AMANDA n
    kernel_configure_variable NF_CONNTRACK_FTP n
    kernel_configure_variable NF_CONNTRACK_H323 n
    kernel_configure_variable NF_CONNTRACK_IRC n
    kernel_configure_variable NF_CONNTRACK_NETBIOS_NS n
    kernel_configure_variable NF_CONNTRACK_SNMP n
    kernel_configure_variable NF_CONNTRACK_PPTP n
    kernel_configure_variable NF_CONNTRACK_SANE n
    kernel_configure_variable NF_CONNTRACK_SIP n
    kernel_configure_variable NF_CONNTRACK_TFTP n
    kernel_configure_variable NF_CT_NETLINK n
    kernel_configure_variable NETFILTER_XT_SET n
    kernel_configure_variable NETFILTER_XT_TARGET_CHECKSUM n
    kernel_configure_variable NETFILTER_XT_TARGET_CLASSIFY n
    kernel_configure_variable NETFILTER_XT_TARGET_CONNMARK n
    kernel_configure_variable NETFILTER_XT_TARGET_DSCP n
    kernel_configure_variable NETFILTER_XT_TARGET_HMARK n
    kernel_configure_variable NETFILTER_XT_TARGET_IDLETIMER n
    kernel_configure_variable NETFILTER_XT_TARGET_LED n
    kernel_configure_variable NETFILTER_XT_TARGET_LOG n
    kernel_configure_variable NETFILTER_XT_TARGET_MARK n
    kernel_configure_variable NETFILTER_XT_TARGET_NFLOG n
    kernel_configure_variable NETFILTER_XT_TARGET_NFQUEUE n
    kernel_configure_variable NETFILTER_XT_TARGET_NOTRACK n
    kernel_configure_variable NETFILTER_XT_TARGET_TEE n
    kernel_configure_variable NETFILTER_XT_TARGET_TPROXY n
    kernel_configure_variable NETFILTER_XT_TARGET_TRACE n
    kernel_configure_variable NETFILTER_XT_TARGET_TCPMSS n
    kernel_configure_variable NETFILTER_XT_TARGET_TCPOPTSTRIP n
    kernel_configure_variable NETFILTER_XT_MATCH_ADDRTYPE n
    kernel_configure_variable NETFILTER_XT_MATCH_BPF n
    kernel_configure_variable NETFILTER_XT_MATCH_CLUSTER n
    kernel_configure_variable NETFILTER_XT_MATCH_COMMENT n
    kernel_configure_variable NETFILTER_XT_MATCH_CONNBYTES n
    kernel_configure_variable NETFILTER_XT_MATCH_CONNLABEL n
    kernel_configure_variable NETFILTER_XT_MATCH_CONNLIMIT n
    kernel_configure_variable NETFILTER_XT_MATCH_CONNMARK n
    kernel_configure_variable NETFILTER_XT_MATCH_CONNTRACK n
    kernel_configure_variable NETFILTER_XT_MATCH_CPU n
    kernel_configure_variable NETFILTER_XT_MATCH_DCCP n
    kernel_configure_variable NETFILTER_XT_MATCH_DEVGROUP n
    kernel_configure_variable NETFILTER_XT_MATCH_DSCP n
    kernel_configure_variable NETFILTER_XT_MATCH_ESP n
    kernel_configure_variable NETFILTER_XT_MATCH_HASHLIMIT n
    kernel_configure_variable NETFILTER_XT_MATCH_HELPER n
    kernel_configure_variable NETFILTER_XT_MATCH_IPRANGE n
    kernel_configure_variable NETFILTER_XT_MATCH_IPVS n
    kernel_configure_variable NETFILTER_XT_MATCH_LENGTH n
    kernel_configure_variable NETFILTER_XT_MATCH_LIMIT n
    kernel_configure_variable NETFILTER_XT_MATCH_MAC n
    kernel_configure_variable NETFILTER_XT_MATCH_MARK n
    kernel_configure_variable NETFILTER_XT_MATCH_MULTIPORT n
    kernel_configure_variable NETFILTER_XT_MATCH_NFACCT n
    kernel_configure_variable NETFILTER_XT_MATCH_OSF n
    kernel_configure_variable NETFILTER_XT_MATCH_OWNER n
    kernel_configure_variable NETFILTER_XT_MATCH_POLICY n
    kernel_configure_variable NETFILTER_XT_MATCH_PHYSDEV n
    kernel_configure_variable NETFILTER_XT_MATCH_PKTTYPE n
    kernel_configure_variable NETFILTER_XT_MATCH_QUOTA n
    kernel_configure_variable NETFILTER_XT_MATCH_RATEEST n
    kernel_configure_variable NETFILTER_XT_MATCH_REALM n
    kernel_configure_variable NETFILTER_XT_MATCH_RECENT n
    kernel_configure_variable NETFILTER_XT_MATCH_SOCKET n
    kernel_configure_variable NETFILTER_XT_MATCH_STATE n
    kernel_configure_variable NETFILTER_XT_MATCH_STATISTIC n
    kernel_configure_variable NETFILTER_XT_MATCH_STRING n
    kernel_configure_variable NETFILTER_XT_MATCH_TCPMSS n
    kernel_configure_variable NETFILTER_XT_MATCH_TIME n
    kernel_configure_variable NETFILTER_XT_MATCH_U32 n
    kernel_configure_variable IP_SET n
    kernel_configure_variable IP_SET_BITMAP_IP n
    kernel_configure_variable IP_SET_BITMAP_IPMAC n
    kernel_configure_variable IP_SET_BITMAP_PORT n
    kernel_configure_variable IP_SET_HASH_IP n
    kernel_configure_variable IP_SET_HASH_IPPORT n
    kernel_configure_variable IP_SET_HASH_IPPORTIP n
    kernel_configure_variable IP_SET_HASH_IPPORTNET n
    kernel_configure_variable IP_SET_HASH_NET n
    kernel_configure_variable IP_SET_HASH_NETPORT n
    kernel_configure_variable IP_SET_HASH_NETIFACE n
    kernel_configure_variable IP_SET_LIST_SET n
    kernel_configure_variable IP_VS n
    kernel_configure_variable IP_VS_RR n
    kernel_configure_variable IP_VS_WRR n
    kernel_configure_variable IP_VS_LC n
    kernel_configure_variable IP_VS_WLC n
    kernel_configure_variable IP_VS_LBLC n
    kernel_configure_variable IP_VS_LBLCR n
    kernel_configure_variable IP_VS_DH n
    kernel_configure_variable IP_VS_SH n
    kernel_configure_variable IP_VS_SED n
    kernel_configure_variable IP_VS_NQ n
    kernel_configure_variable IP_VS_FTP n
    kernel_configure_variable IP_VS_PE_SIP n
    kernel_configure_variable NF_CONNTRACK_IPV4 n
    kernel_configure_variable IP_NF_IPTABLES n
    kernel_configure_variable IP_NF_MATCH_AH n
    kernel_configure_variable IP_NF_MATCH_ECN n
    kernel_configure_variable IP_NF_MATCH_RPFILTER n
    kernel_configure_variable IP_NF_MATCH_TTL n
    kernel_configure_variable IP_NF_FILTER n
    kernel_configure_variable IP_NF_TARGET_REJECT n
    kernel_configure_variable IP_NF_NAT n
    kernel_configure_variable IP_NF_TARGET_MASQUERADE n
    kernel_configure_variable IP_NF_TARGET_NETMAP n
    kernel_configure_variable IP_NF_TARGET_REDIRECT n
    kernel_configure_variable IP_NF_MANGLE n
    kernel_configure_variable IP_NF_TARGET_CLUSTERIP n
    kernel_configure_variable IP_NF_TARGET_ECN n
    kernel_configure_variable IP_NF_TARGET_TTL n
    kernel_configure_variable IP_NF_RAW n
    kernel_configure_variable IP_NF_ARPTABLES n
    kernel_configure_variable IP_NF_ARPFILTER n
    kernel_configure_variable IP_NF_ARP_MANGLE n
    kernel_configure_variable NF_CONNTRACK_IPV6 n
    kernel_configure_variable IP6_NF_IPTABLES n
    kernel_configure_variable IP6_NF_MATCH_AH n
    kernel_configure_variable IP6_NF_MATCH_EUI64 n
    kernel_configure_variable IP6_NF_MATCH_FRAG n
    kernel_configure_variable IP6_NF_MATCH_OPTS n
    kernel_configure_variable IP6_NF_MATCH_HL n
    kernel_configure_variable IP6_NF_MATCH_IPV6HEADER n
    kernel_configure_variable IP6_NF_MATCH_MH n
    kernel_configure_variable IP6_NF_MATCH_RPFILTER n
    kernel_configure_variable IP6_NF_MATCH_RT n
    kernel_configure_variable IP6_NF_TARGET_HL n
    kernel_configure_variable IP6_NF_FILTER n
    kernel_configure_variable IP6_NF_TARGET_REJECT n
    kernel_configure_variable IP6_NF_MANGLE n
    kernel_configure_variable IP6_NF_RAW n
    kernel_configure_variable IP6_NF_NAT n
    kernel_configure_variable IP6_NF_TARGET_MASQUERADE n
    kernel_configure_variable IP6_NF_TARGET_NPT n
    kernel_configure_variable BRIDGE_NF_EBTABLES n
    kernel_configure_variable BRIDGE_EBT_BROUTE n
    kernel_configure_variable BRIDGE_EBT_T_FILTER n
    kernel_configure_variable BRIDGE_EBT_T_NAT n
    kernel_configure_variable BRIDGE_EBT_802_3 n
    kernel_configure_variable BRIDGE_EBT_AMONG n
    kernel_configure_variable BRIDGE_EBT_ARP n
    kernel_configure_variable BRIDGE_EBT_IP n
    kernel_configure_variable BRIDGE_EBT_IP6 n
    kernel_configure_variable BRIDGE_EBT_LIMIT n
    kernel_configure_variable BRIDGE_EBT_MARK n
    kernel_configure_variable BRIDGE_EBT_PKTTYPE n
    kernel_configure_variable BRIDGE_EBT_STP n
    kernel_configure_variable BRIDGE_EBT_VLAN n
    kernel_configure_variable BRIDGE_EBT_ARPREPLY n
    kernel_configure_variable BRIDGE_EBT_DNAT n
    kernel_configure_variable BRIDGE_EBT_MARK_T n
    kernel_configure_variable BRIDGE_EBT_REDIRECT n
    kernel_configure_variable BRIDGE_EBT_SNAT n
    kernel_configure_variable BRIDGE_EBT_LOG n
    kernel_configure_variable BRIDGE_EBT_NFLOG n
    kernel_configure_variable ATM n
    kernel_configure_variable L2TP n
    kernel_configure_variable L2TP_IP n
    kernel_configure_variable L2TP_ETH n
    kernel_configure_variable BRIDGE n
    kernel_configure_variable VLAN_8021Q n
    kernel_configure_variable ATALK n
    kernel_configure_variable 6LOWPAN n
    kernel_configure_variable IEEE802154 n
    kernel_configure_variable IEEE802154_6LOWPAN n
    kernel_configure_variable MAC802154 n
    kernel_configure_variable NET_SCH_CBQ n
    kernel_configure_variable NET_SCH_HTB n
    kernel_configure_variable NET_SCH_HFSC n
    kernel_configure_variable NET_SCH_ATM n
    kernel_configure_variable NET_SCH_PRIO n
    kernel_configure_variable NET_SCH_MULTIQ n
    kernel_configure_variable NET_SCH_RED n
    kernel_configure_variable NET_SCH_SFB n
    kernel_configure_variable NET_SCH_SFQ n
    kernel_configure_variable NET_SCH_TEQL n
    kernel_configure_variable NET_SCH_TBF n
    kernel_configure_variable NET_SCH_GRED n
    kernel_configure_variable NET_SCH_DSMARK n
    kernel_configure_variable NET_SCH_NETEM n
    kernel_configure_variable NET_SCH_DRR n
    kernel_configure_variable NET_SCH_MQPRIO n
    kernel_configure_variable NET_SCH_CHOKE n
    kernel_configure_variable NET_SCH_QFQ n
    kernel_configure_variable NET_SCH_CODEL n
    kernel_configure_variable NET_SCH_FQ_CODEL n
    kernel_configure_variable NET_SCH_FQ n
    kernel_configure_variable NET_SCH_HHF n
    kernel_configure_variable NET_SCH_PIE n
    kernel_configure_variable NET_SCH_INGRESS n
    kernel_configure_variable NET_SCH_PLUG n
    kernel_configure_variable NET_CLS_BASIC n
    kernel_configure_variable NET_CLS_TCINDEX n
    kernel_configure_variable NET_CLS_ROUTE4 n
    kernel_configure_variable NET_CLS_FW n
    kernel_configure_variable NET_CLS_U32 n
    kernel_configure_variable NET_CLS_RSVP n
    kernel_configure_variable NET_CLS_RSVP6 n
    kernel_configure_variable NET_CLS_FLOW n
    kernel_configure_variable NET_CLS_CGROUP n
    kernel_configure_variable NET_EMATCH_CMP n
    kernel_configure_variable NET_EMATCH_NBYTE n
    kernel_configure_variable NET_EMATCH_U32 n
    kernel_configure_variable NET_EMATCH_META n
    kernel_configure_variable NET_EMATCH_TEXT n
    kernel_configure_variable NET_EMATCH_IPSET n
    kernel_configure_variable NET_ACT_POLICE n
    kernel_configure_variable NET_ACT_GACT n
    kernel_configure_variable NET_ACT_MIRRED n
    kernel_configure_variable NET_ACT_IPT n
    kernel_configure_variable NET_ACT_NAT n
    kernel_configure_variable NET_ACT_PEDIT n
    kernel_configure_variable NET_ACT_SIMP n
    kernel_configure_variable NET_ACT_SKBEDIT n
    kernel_configure_variable NET_ACT_CSUM n
    kernel_configure_variable BATMAN_ADV n
    kernel_configure_variable OPENVSWITCH n
    kernel_configure_variable NET_PKTGEN n
    kernel_configure_variable AX25 n
    kernel_configure_variable NETROM n
    kernel_configure_variable ROSE n
    kernel_configure_variable MKISS n
    kernel_configure_variable 6PACK n
    kernel_configure_variable BPQETHER n
    kernel_configure_variable BAYCOM_SER_FDX n
    kernel_configure_variable BAYCOM_SER_HDX n
    kernel_configure_variable YAM n
    kernel_configure_variable CAN n
    kernel_configure_variable CAN_VCAN n
    kernel_configure_variable CAN_SLCAN n
    kernel_configure_variable CAN_MCP251X n
    kernel_configure_variable CAN_GS_USB n
    kernel_configure_variable IRDA n
    kernel_configure_variable IRLAN n
    kernel_configure_variable IRNET n
    kernel_configure_variable IRCOMM n
    kernel_configure_variable IRTTY_SIR n
    kernel_configure_variable KINGSUN_DONGLE n
    kernel_configure_variable KSDAZZLE_DONGLE n
    kernel_configure_variable KS959_DONGLE n
    kernel_configure_variable USB_IRDA n
    kernel_configure_variable SIGMATEL_FIR n
    kernel_configure_variable MCS_FIR n
    kernel_configure_variable BT n
    kernel_configure_variable BT_RFCOMM n
    kernel_configure_variable BT_BNEP n
    kernel_configure_variable BT_HIDP n
    kernel_configure_variable BT_6LOWPAN n
    kernel_configure_variable BT_HCIBTUSB n
    kernel_configure_variable BT_HCIUART n
    kernel_configure_variable BT_HCIBCM203X n
    kernel_configure_variable BT_HCIBPA10X n
    kernel_configure_variable BT_HCIBFUSB n
    kernel_configure_variable BT_HCIVHCI n
    kernel_configure_variable BT_MRVL n
    kernel_configure_variable BT_MRVL_SDIO n
    kernel_configure_variable BT_ATH3K n
    kernel_configure_variable BT_WILINK n
    kernel_configure_variable CFG80211 n
    kernel_configure_variable MAC80211 n
    kernel_configure_variable WIMAX n
    kernel_configure_variable RFKILL n
    kernel_configure_variable NET_9P n
    kernel_configure_variable NFC n
    kernel_configure_variable MTD n
    kernel_configure_variable MTD_BLOCK n
    kernel_configure_variable MTD_M25P80 n
    kernel_configure_variable MTD_NAND n
    kernel_configure_variable MTD_SPI_NOR n
    kernel_configure_variable MTD_UBI n
    kernel_configure_variable ZRAM n
    kernel_configure_variable BLK_DEV_CRYPTOLOOP n
    kernel_configure_variable BLK_DEV_DRBD n
    kernel_configure_variable BLK_DEV_NBD n
    kernel_configure_variable CDROM_PKTCDVD n
    kernel_configure_variable ATA_OVER_ETH n
    kernel_configure_variable EEPROM_AT24 n
    kernel_configure_variable TI_ST n
    kernel_configure_variable CHR_DEV_ST n
    kernel_configure_variable CHR_DEV_OSST n
    kernel_configure_variable BLK_DEV_SR n
    kernel_configure_variable CHR_DEV_SG n
    kernel_configure_variable ISCSI_TCP n
    kernel_configure_variable ISCSI_BOOT_SYSFS n
    kernel_configure_variable MD_LINEAR n
    kernel_configure_variable BLK_DEV_DM n
    kernel_configure_variable DM_CRYPT n
    kernel_configure_variable DM_SNAPSHOT n
    kernel_configure_variable DM_THIN_PROVISIONING n
    kernel_configure_variable DM_MIRROR n
    kernel_configure_variable DM_LOG_USERSPACE n
    kernel_configure_variable DM_RAID n
    kernel_configure_variable DM_ZERO n
    kernel_configure_variable DM_DELAY n
    kernel_configure_variable BONDING n
    kernel_configure_variable DUMMY n
    kernel_configure_variable IFB n
    kernel_configure_variable MACVLAN n
    kernel_configure_variable VXLAN n
    kernel_configure_variable NETCONSOLE n
    kernel_configure_variable TUN n
    kernel_configure_variable VETH n
    kernel_configure_variable ENC28J60 n
    kernel_configure_variable QCA7000 n
    kernel_configure_variable MDIO_BITBANG n
    kernel_configure_variable PPP n
    kernel_configure_variable PPP_BSDCOMP n
    kernel_configure_variable PPP_DEFLATE n
    kernel_configure_variable PPP_MPPE n
    kernel_configure_variable PPPOATM n
    kernel_configure_variable PPPOE n
    kernel_configure_variable PPPOL2TP n
    kernel_configure_variable PPP_ASYNC n
    kernel_configure_variable PPP_SYNC_TTY n
    kernel_configure_variable SLIP n
    kernel_configure_variable USB_CATC n
    kernel_configure_variable USB_KAWETH n
    kernel_configure_variable USB_PEGASUS n
    kernel_configure_variable USB_RTL8150 n
    kernel_configure_variable USB_RTL8152 n
    kernel_configure_variable USB_LAN78XX y
    kernel_configure_variable USB_NET_AX8817X n
    kernel_configure_variable USB_NET_AX88179_178A n
    kernel_configure_variable USB_NET_CDCETHER n
    kernel_configure_variable USB_NET_CDC_EEM n
    kernel_configure_variable USB_NET_CDC_NCM n
    kernel_configure_variable USB_NET_HUAWEI_CDC_NCM n
    kernel_configure_variable USB_NET_CDC_MBIM n
    kernel_configure_variable USB_NET_DM9601 n
    kernel_configure_variable USB_NET_SR9700 n
    kernel_configure_variable USB_NET_SR9800 n
    kernel_configure_variable USB_NET_SMSC75XX n
    kernel_configure_variable USB_NET_GL620A n
    kernel_configure_variable USB_NET_NET1080 n
    kernel_configure_variable USB_NET_PLUSB n
    kernel_configure_variable USB_NET_MCS7830 n
    kernel_configure_variable USB_NET_CDC_SUBSET n
    kernel_configure_variable USB_NET_ZAURUS n
    kernel_configure_variable USB_NET_CX82310_ETH n
    kernel_configure_variable USB_NET_KALMIA n
    kernel_configure_variable USB_NET_QMI_WWAN n
    kernel_configure_variable USB_HSO n
    kernel_configure_variable USB_NET_INT51X1 n
    kernel_configure_variable USB_IPHETH n
    kernel_configure_variable USB_SIERRA_NET n
    kernel_configure_variable USB_VL600 n
    kernel_configure_variable ATH9K n
    kernel_configure_variable ATH9K_HTC n
    kernel_configure_variable CARL9170 n
    kernel_configure_variable ATH6KL n
    kernel_configure_variable ATH6KL_USB n
    kernel_configure_variable AR5523 n
    kernel_configure_variable AT76C50X_USB n
    kernel_configure_variable B43 n
    kernel_configure_variable B43LEGACY n
    kernel_configure_variable BRCMFMAC m
    kernel_configure_variable HOSTAP n
    kernel_configure_variable P54_COMMON n
    kernel_configure_variable P54_USB n
    kernel_configure_variable LIBERTAS n
    kernel_configure_variable LIBERTAS_USB n
    kernel_configure_variable LIBERTAS_SDIO n
    kernel_configure_variable LIBERTAS_THINFIRM n
    kernel_configure_variable LIBERTAS_THINFIRM_USB n
    kernel_configure_variable MWIFIEX n
    kernel_configure_variable MWIFIEX_SDIO n
    kernel_configure_variable MT7601U n
    kernel_configure_variable RT2X00 n
    kernel_configure_variable RT2500USB n
    kernel_configure_variable RT73USB n
    kernel_configure_variable RT2800USB n
    kernel_configure_variable RTL8187 n
    kernel_configure_variable RTL8192CU n
    kernel_configure_variable RTL8XXXU n
    kernel_configure_variable USB_ZD1201 n
    kernel_configure_variable ZD1211RW n
    kernel_configure_variable MAC80211_HWSIM n
    kernel_configure_variable USB_NET_RNDIS_WLAN n
    kernel_configure_variable WIMAX_I2400M_USB n
    kernel_configure_variable IEEE802154_AT86RF230 n
    kernel_configure_variable IEEE802154_MRF24J40 n
    kernel_configure_variable IEEE802154_CC2520 n
    kernel_configure_variable INPUT_POLLDEV n
    kernel_configure_variable INPUT_JOYDEV n
    kernel_configure_variable INPUT_EVDEV n
    kernel_configure_variable KEYBOARD_GPIO n
    kernel_configure_variable JOYSTICK_IFORCE n
    kernel_configure_variable JOYSTICK_XPAD n
    kernel_configure_variable JOYSTICK_RPISENSE n
    kernel_configure_variable TOUCHSCREEN_ADS7846 n
    kernel_configure_variable TOUCHSCREEN_EGALAX n
    kernel_configure_variable TOUCHSCREEN_EXC3000 n
    kernel_configure_variable TOUCHSCREEN_GOODIX n
    kernel_configure_variable TOUCHSCREEN_EDT_FT5X06 n
    kernel_configure_variable TOUCHSCREEN_RPI_FT5406 n
    kernel_configure_variable TOUCHSCREEN_USB_COMPOSITE n
    kernel_configure_variable TOUCHSCREEN_STMPE n
    kernel_configure_variable INPUT_AD714X n
    kernel_configure_variable INPUT_ATI_REMOTE2 n
    kernel_configure_variable INPUT_KEYSPAN_REMOTE n
    kernel_configure_variable INPUT_POWERMATE n
    kernel_configure_variable INPUT_YEALINK n
    kernel_configure_variable INPUT_CM109 n
    kernel_configure_variable INPUT_UINPUT n
    kernel_configure_variable INPUT_GPIO_ROTARY_ENCODER n
    kernel_configure_variable INPUT_ADXL34X n
    kernel_configure_variable INPUT_CMA3000 n
    kernel_configure_variable SERIO n
    kernel_configure_variable SERIO_RAW n
    kernel_configure_variable GAMEPORT n
    kernel_configure_variable GAMEPORT_NS558 n
    kernel_configure_variable GAMEPORT_L4 n
    kernel_configure_variable SERIAL_SC16IS7XX n
    kernel_configure_variable I2C_CHARDEV n
    kernel_configure_variable I2C_MUX_PCA954x n
    kernel_configure_variable I2C_BCM2708 n
    kernel_configure_variable I2C_GPIO n
    kernel_configure_variable I2C_ROBOTFUZZ_OSIF n
    kernel_configure_variable SPI_BCM2835 n
    kernel_configure_variable SPI_BCM2835AUX n
    kernel_configure_variable SPI_SPIDEV n
    kernel_configure_variable PPS n
    kernel_configure_variable PPS_CLIENT_LDISC n
    kernel_configure_variable PPS_CLIENT_GPIO n
    kernel_configure_variable GPIO_PCF857X n
    kernel_configure_variable GPIO_ARIZONA n
    kernel_configure_variable GPIO_MCP23S08 n
    kernel_configure_variable W1 n
    kernel_configure_variable W1_MASTER_DS2490 n
    kernel_configure_variable W1_MASTER_DS2482 n
    kernel_configure_variable W1_MASTER_DS1WM n
    kernel_configure_variable W1_MASTER_GPIO n
    kernel_configure_variable W1_SLAVE_THERM n
    kernel_configure_variable W1_SLAVE_SMEM n
    kernel_configure_variable W1_SLAVE_DS2408 n
    kernel_configure_variable W1_SLAVE_DS2413 n
    kernel_configure_variable W1_SLAVE_DS2406 n
    kernel_configure_variable W1_SLAVE_DS2423 n
    kernel_configure_variable W1_SLAVE_DS2431 n
    kernel_configure_variable W1_SLAVE_DS2433 n
    kernel_configure_variable W1_SLAVE_DS2438 n
    kernel_configure_variable W1_SLAVE_DS2760 n
    kernel_configure_variable W1_SLAVE_DS2780 n
    kernel_configure_variable W1_SLAVE_DS2781 n
    kernel_configure_variable W1_SLAVE_DS28E04 n
    kernel_configure_variable W1_SLAVE_BQ27000 n
    kernel_configure_variable BATTERY_DS2760 n
    kernel_configure_variable HWMON n
    kernel_configure_variable SENSORS_JC42 n
    kernel_configure_variable SENSORS_LM75 n
    kernel_configure_variable SENSORS_SHT21 n
    kernel_configure_variable SENSORS_SHT3x n
    kernel_configure_variable SENSORS_SHTC1 n
    kernel_configure_variable SENSORS_ADS1015 n
    kernel_configure_variable SENSORS_INA2XX n
    kernel_configure_variable SENSORS_TMP102 n
    kernel_configure_variable GPIO_WATCHDOG n
    kernel_configure_variable UCB1400_CORE n
    kernel_configure_variable MFD_ARIZONA_I2C n
    kernel_configure_variable MFD_ARIZONA_SPI n
    kernel_configure_variable REGULATOR_FIXED_VOLTAGE n
    kernel_configure_variable REGULATOR_ARIZONA n
    kernel_configure_variable MEDIA_SUPPORT n
    kernel_configure_variable LIRC n
    kernel_configure_variable RC_ATI_REMOTE n
    kernel_configure_variable IR_IMON n
    kernel_configure_variable IR_MCEUSB n
    kernel_configure_variable IR_REDRAT3 n
    kernel_configure_variable IR_STREAMZAP n
    kernel_configure_variable IR_IGUANA n
    kernel_configure_variable IR_TTUSBIR n
    kernel_configure_variable RC_LOOPBACK n
    kernel_configure_variable IR_GPIO_CIR n
    kernel_configure_variable USB_VIDEO_CLASS n
    kernel_configure_variable USB_M5602 n
    kernel_configure_variable USB_STV06XX n
    kernel_configure_variable USB_GL860 n
    kernel_configure_variable USB_GSPCA_BENQ n
    kernel_configure_variable USB_GSPCA_CONEX n
    kernel_configure_variable USB_GSPCA_CPIA1 n
    kernel_configure_variable USB_GSPCA_DTCS033 n
    kernel_configure_variable USB_GSPCA_ETOMS n
    kernel_configure_variable USB_GSPCA_FINEPIX n
    kernel_configure_variable USB_GSPCA_JEILINJ n
    kernel_configure_variable USB_GSPCA_JL2005BCD n
    kernel_configure_variable USB_GSPCA_KINECT n
    kernel_configure_variable USB_GSPCA_KONICA n
    kernel_configure_variable USB_GSPCA_MARS n
    kernel_configure_variable USB_GSPCA_MR97310A n
    kernel_configure_variable USB_GSPCA_NW80X n
    kernel_configure_variable USB_GSPCA_OV519 n
    kernel_configure_variable USB_GSPCA_OV534 n
    kernel_configure_variable USB_GSPCA_OV534_9 n
    kernel_configure_variable USB_GSPCA_PAC207 n
    kernel_configure_variable USB_GSPCA_PAC7302 n
    kernel_configure_variable USB_GSPCA_PAC7311 n
    kernel_configure_variable USB_GSPCA_SE401 n
    kernel_configure_variable USB_GSPCA_SN9C2028 n
    kernel_configure_variable USB_GSPCA_SN9C20X n
    kernel_configure_variable USB_GSPCA_SONIXB n
    kernel_configure_variable USB_GSPCA_SONIXJ n
    kernel_configure_variable USB_GSPCA_SPCA500 n
    kernel_configure_variable USB_GSPCA_SPCA501 n
    kernel_configure_variable USB_GSPCA_SPCA505 n
    kernel_configure_variable USB_GSPCA_SPCA506 n
    kernel_configure_variable USB_GSPCA_SPCA508 n
    kernel_configure_variable USB_GSPCA_SPCA561 n
    kernel_configure_variable USB_GSPCA_SPCA1528 n
    kernel_configure_variable USB_GSPCA_SQ905 n
    kernel_configure_variable USB_GSPCA_SQ905C n
    kernel_configure_variable USB_GSPCA_SQ930X n
    kernel_configure_variable USB_GSPCA_STK014 n
    kernel_configure_variable USB_GSPCA_STK1135 n
    kernel_configure_variable USB_GSPCA_STV0680 n
    kernel_configure_variable USB_GSPCA_SUNPLUS n
    kernel_configure_variable USB_GSPCA_T613 n
    kernel_configure_variable USB_GSPCA_TOPRO n
    kernel_configure_variable USB_GSPCA_TV8532 n
    kernel_configure_variable USB_GSPCA_VC032X n
    kernel_configure_variable USB_GSPCA_VICAM n
    kernel_configure_variable USB_GSPCA_XIRLINK_CIT n
    kernel_configure_variable USB_GSPCA_ZC3XX n
    kernel_configure_variable USB_PWC n
    kernel_configure_variable VIDEO_CPIA2 n
    kernel_configure_variable USB_ZR364XX n
    kernel_configure_variable USB_STKWEBCAM n
    kernel_configure_variable USB_S2255 n
    kernel_configure_variable VIDEO_USBTV n
    kernel_configure_variable VIDEO_PVRUSB2 n
    kernel_configure_variable VIDEO_HDPVR n
    kernel_configure_variable VIDEO_USBVISION n
    kernel_configure_variable VIDEO_STK1160_COMMON n
    kernel_configure_variable VIDEO_GO7007 n
    kernel_configure_variable VIDEO_GO7007_USB n
    kernel_configure_variable VIDEO_GO7007_USB_S2250_BOARD n
    kernel_configure_variable VIDEO_AU0828 n
    kernel_configure_variable VIDEO_CX231XX n
    kernel_configure_variable VIDEO_CX231XX_ALSA n
    kernel_configure_variable VIDEO_CX231XX_DVB n
    kernel_configure_variable VIDEO_TM6000 n
    kernel_configure_variable VIDEO_TM6000_ALSA n
    kernel_configure_variable VIDEO_TM6000_DVB n
    kernel_configure_variable DVB_USB n
    kernel_configure_variable DVB_USB_A800 n
    kernel_configure_variable DVB_USB_DIBUSB_MB n
    kernel_configure_variable DVB_USB_DIBUSB_MC n
    kernel_configure_variable DVB_USB_DIB0700 n
    kernel_configure_variable DVB_USB_UMT_010 n
    kernel_configure_variable DVB_USB_CXUSB n
    kernel_configure_variable DVB_USB_M920X n
    kernel_configure_variable DVB_USB_DIGITV n
    kernel_configure_variable DVB_USB_VP7045 n
    kernel_configure_variable DVB_USB_VP702X n
    kernel_configure_variable DVB_USB_GP8PSK n
    kernel_configure_variable DVB_USB_NOVA_T_USB2 n
    kernel_configure_variable DVB_USB_TTUSB2 n
    kernel_configure_variable DVB_USB_DTT200U n
    kernel_configure_variable DVB_USB_OPERA1 n
    kernel_configure_variable DVB_USB_AF9005 n
    kernel_configure_variable DVB_USB_AF9005_REMOTE n
    kernel_configure_variable DVB_USB_PCTV452E n
    kernel_configure_variable DVB_USB_DW2102 n
    kernel_configure_variable DVB_USB_CINERGY_T2 n
    kernel_configure_variable DVB_USB_DTV5100 n
    kernel_configure_variable DVB_USB_FRIIO n
    kernel_configure_variable DVB_USB_AZ6027 n
    kernel_configure_variable DVB_USB_TECHNISAT_USB2 n
    kernel_configure_variable DVB_USB_V2 n
    kernel_configure_variable DVB_USB_AF9015 n
    kernel_configure_variable DVB_USB_AF9035 n
    kernel_configure_variable DVB_USB_ANYSEE n
    kernel_configure_variable DVB_USB_AU6610 n
    kernel_configure_variable DVB_USB_AZ6007 n
    kernel_configure_variable DVB_USB_CE6230 n
    kernel_configure_variable DVB_USB_EC168 n
    kernel_configure_variable DVB_USB_GL861 n
    kernel_configure_variable DVB_USB_LME2510 n
    kernel_configure_variable DVB_USB_MXL111SF n
    kernel_configure_variable DVB_USB_RTL28XXU n
    kernel_configure_variable DVB_USB_DVBSKY n
    kernel_configure_variable SMS_USB_DRV n
    kernel_configure_variable DVB_B2C2_FLEXCOP_USB n
    kernel_configure_variable DVB_AS102 n
    kernel_configure_variable VIDEO_EM28XX n
    kernel_configure_variable VIDEO_EM28XX_V4L2 n
    kernel_configure_variable VIDEO_EM28XX_ALSA n
    kernel_configure_variable VIDEO_EM28XX_DVB n
    kernel_configure_variable VIDEO_BCM2835_MMAL n
    kernel_configure_variable USB_SI470X n
    kernel_configure_variable I2C_SI470X n
    kernel_configure_variable RADIO_SI4713 n
    kernel_configure_variable I2C_SI4713 n
    kernel_configure_variable USB_MR800 n
    kernel_configure_variable USB_DSBR n
    kernel_configure_variable RADIO_SHARK n
    kernel_configure_variable RADIO_SHARK2 n
    kernel_configure_variable USB_KEENE n
    kernel_configure_variable USB_MA901 n
    kernel_configure_variable RADIO_TEA5764 n
    kernel_configure_variable RADIO_SAA7706H n
    kernel_configure_variable RADIO_TEF6862 n
    kernel_configure_variable RADIO_WL1273 n
    kernel_configure_variable RADIO_WL128X n
    kernel_configure_variable VIDEO_UDA1342 n
    kernel_configure_variable VIDEO_SONY_BTF_MPX n
    kernel_configure_variable VIDEO_TVP5150 n
    kernel_configure_variable VIDEO_TW2804 n
    kernel_configure_variable VIDEO_TW9903 n
    kernel_configure_variable VIDEO_TW9906 n
    kernel_configure_variable VIDEO_OV7640 n
    kernel_configure_variable VIDEO_MT9V011 n
    kernel_configure_variable DRM_UDL n
    kernel_configure_variable DRM_PANEL_SIMPLE n
    kernel_configure_variable DRM_PANEL_RASPBERRYPI_TOUCHSCREEN n
    kernel_configure_variable DRM_TINYDRM n
    kernel_configure_variable TINYDRM_MI0283QT n
    kernel_configure_variable TINYDRM_REPAPER n
    kernel_configure_variable FB_UDL n
    kernel_configure_variable FB_SSD1307 n
    kernel_configure_variable FB_RPISENSE n
    kernel_configure_variable BACKLIGHT_RPI n
    kernel_configure_variable BACKLIGHT_GPIO n
    kernel_configure_variable SND_SEQUENCER n
    kernel_configure_variable SND_SEQ_DUMMY n
    kernel_configure_variable SND_MIXER_OSS n
    kernel_configure_variable SND_PCM_OSS n
    kernel_configure_variable SND_HRTIMER n
    kernel_configure_variable SND_DUMMY n
    kernel_configure_variable SND_ALOOP n
    kernel_configure_variable SND_VIRMIDI n
    kernel_configure_variable SND_MTPAV n
    kernel_configure_variable SND_SERIAL_U16550 n
    kernel_configure_variable SND_MPU401 n
    kernel_configure_variable SND_USB_AUDIO n
    kernel_configure_variable SND_USB_UA101 n
    kernel_configure_variable SND_USB_CAIAQ n
    kernel_configure_variable SND_USB_6FIRE n
    kernel_configure_variable SND_USB_HIFACE n
    kernel_configure_variable SND_BCM2708_SOC_GOOGLEVOICEHAT_SOUNDCARD n
    kernel_configure_variable SND_BCM2708_SOC_HIFIBERRY_DAC n
    kernel_configure_variable SND_BCM2708_SOC_HIFIBERRY_DACPLUS n
    kernel_configure_variable SND_BCM2708_SOC_HIFIBERRY_DIGI n
    kernel_configure_variable SND_BCM2708_SOC_HIFIBERRY_AMP n
    kernel_configure_variable SND_BCM2708_SOC_RPI_CIRRUS n
    kernel_configure_variable SND_BCM2708_SOC_RPI_DAC n
    kernel_configure_variable SND_BCM2708_SOC_RPI_PROTO n
    kernel_configure_variable SND_BCM2708_SOC_JUSTBOOM_DAC n
    kernel_configure_variable SND_BCM2708_SOC_JUSTBOOM_DIGI n
    kernel_configure_variable SND_BCM2708_SOC_IQAUDIO_DAC n
    kernel_configure_variable SND_BCM2708_SOC_IQAUDIO_DIGI n
    kernel_configure_variable SND_BCM2708_SOC_RASPIDAC3 n
    kernel_configure_variable SND_BCM2708_SOC_ADAU1977_ADC n
    kernel_configure_variable SND_AUDIOINJECTOR_PI_SOUNDCARD n
    kernel_configure_variable SND_AUDIOINJECTOR_OCTO_SOUNDCARD n
    kernel_configure_variable SND_DIGIDAC1_SOUNDCARD n
    kernel_configure_variable SND_BCM2708_SOC_DIONAUDIO_LOCO n
    kernel_configure_variable SND_BCM2708_SOC_DIONAUDIO_LOCO_V2 n
    kernel_configure_variable SND_BCM2708_SOC_ALLO_PIANO_DAC n
    kernel_configure_variable SND_BCM2708_SOC_ALLO_PIANO_DAC_PLUS n
    kernel_configure_variable SND_BCM2708_SOC_FE_PI_AUDIO n
    kernel_configure_variable SND_BCM2708_SOC_ALLO_BOSS_DAC n
    kernel_configure_variable SND_BCM2708_SOC_ALLO_DIGIONE n
    kernel_configure_variable SND_PISOUND n
    kernel_configure_variable SND_SOC_ADAU1701 n
    kernel_configure_variable SND_SOC_ADAU7002 n
    kernel_configure_variable SND_SOC_AK4554 n
    kernel_configure_variable SND_SOC_SPDIF n
    kernel_configure_variable SND_SOC_WM8804_I2C n
    kernel_configure_variable SND_SIMPLE_CARD n
    kernel_configure_variable SOUND_PRIME n
    kernel_configure_variable UHID n
    kernel_configure_variable HID_A4TECH n
    kernel_configure_variable HID_ACRUX n
    kernel_configure_variable HID_APPLE n
    kernel_configure_variable HID_BELKIN n
    kernel_configure_variable HID_BETOP_FF n
    kernel_configure_variable HID_CHERRY n
    kernel_configure_variable HID_CHICONY n
    kernel_configure_variable HID_CYPRESS n
    kernel_configure_variable HID_DRAGONRISE n
    kernel_configure_variable HID_EMS_FF n
    kernel_configure_variable HID_ELECOM n
    kernel_configure_variable HID_ELO n
    kernel_configure_variable HID_EZKEY n
    kernel_configure_variable HID_GEMBIRD n
    kernel_configure_variable HID_HOLTEK n
    kernel_configure_variable HID_KEYTOUCH n
    kernel_configure_variable HID_KYE n
    kernel_configure_variable HID_UCLOGIC n
    kernel_configure_variable HID_WALTOP n
    kernel_configure_variable HID_GYRATION n
    kernel_configure_variable HID_TWINHAN n
    kernel_configure_variable HID_KENSINGTON n
    kernel_configure_variable HID_LCPOWER n
    kernel_configure_variable HID_LOGITECH n
    kernel_configure_variable HID_LOGITECH_DJ n
    kernel_configure_variable HID_MAGICMOUSE n
    kernel_configure_variable HID_MICROSOFT n
    kernel_configure_variable HID_MONTEREY n
    kernel_configure_variable HID_MULTITOUCH n
    kernel_configure_variable HID_NTRIG n
    kernel_configure_variable HID_ORTEK n
    kernel_configure_variable HID_PANTHERLORD n
    kernel_configure_variable HID_PETALYNX n
    kernel_configure_variable HID_PICOLCD n
    kernel_configure_variable HID_ROCCAT n
    kernel_configure_variable HID_SAMSUNG n
    kernel_configure_variable HID_SONY n
    kernel_configure_variable HID_SPEEDLINK n
    kernel_configure_variable HID_SUNPLUS n
    kernel_configure_variable HID_GREENASIA n
    kernel_configure_variable HID_SMARTJOYPLUS n
    kernel_configure_variable HID_TOPSEED n
    kernel_configure_variable HID_THINGM n
    kernel_configure_variable HID_THRUSTMASTER n
    kernel_configure_variable HID_WACOM n
    kernel_configure_variable HID_WIIMOTE n
    kernel_configure_variable HID_XINMO n
    kernel_configure_variable HID_ZEROPLUS n
    kernel_configure_variable HID_ZYDACRON n
    kernel_configure_variable USB_MON n
    kernel_configure_variable USB_PRINTER n
    kernel_configure_variable USB_STORAGE_REALTEK n
    kernel_configure_variable USB_STORAGE_DATAFAB n
    kernel_configure_variable USB_STORAGE_FREECOM n
    kernel_configure_variable USB_STORAGE_ISD200 n
    kernel_configure_variable USB_STORAGE_USBAT n
    kernel_configure_variable USB_STORAGE_SDDR09 n
    kernel_configure_variable USB_STORAGE_SDDR55 n
    kernel_configure_variable USB_STORAGE_JUMPSHOT n
    kernel_configure_variable USB_STORAGE_ALAUDA n
    kernel_configure_variable USB_STORAGE_ONETOUCH n
    kernel_configure_variable USB_STORAGE_KARMA n
    kernel_configure_variable USB_STORAGE_CYPRESS_ATACB n
    kernel_configure_variable USB_STORAGE_ENE_UB6250 n
    kernel_configure_variable USB_MDC800 n
    kernel_configure_variable USB_MICROTEK n
    kernel_configure_variable USBIP_CORE n
    kernel_configure_variable USBIP_VHCI_HCD n
    kernel_configure_variable USBIP_HOST n
    kernel_configure_variable USB_SERIAL n
    kernel_configure_variable USB_SERIAL_AIRCABLE n
    kernel_configure_variable USB_SERIAL_ARK3116 n
    kernel_configure_variable USB_SERIAL_BELKIN n
    kernel_configure_variable USB_SERIAL_CH341 n
    kernel_configure_variable USB_SERIAL_WHITEHEAT n
    kernel_configure_variable USB_SERIAL_DIGI_ACCELEPORT n
    kernel_configure_variable USB_SERIAL_CP210X n
    kernel_configure_variable USB_SERIAL_CYPRESS_M8 n
    kernel_configure_variable USB_SERIAL_EMPEG n
    kernel_configure_variable USB_SERIAL_FTDI_SIO n
    kernel_configure_variable USB_SERIAL_VISOR n
    kernel_configure_variable USB_SERIAL_IPAQ n
    kernel_configure_variable USB_SERIAL_IR n
    kernel_configure_variable USB_SERIAL_EDGEPORT n
    kernel_configure_variable USB_SERIAL_EDGEPORT_TI n
    kernel_configure_variable USB_SERIAL_F81232 n
    kernel_configure_variable USB_SERIAL_GARMIN n
    kernel_configure_variable USB_SERIAL_IPW n
    kernel_configure_variable USB_SERIAL_IUU n
    kernel_configure_variable USB_SERIAL_KEYSPAN_PDA n
    kernel_configure_variable USB_SERIAL_KEYSPAN n
    kernel_configure_variable USB_SERIAL_KLSI n
    kernel_configure_variable USB_SERIAL_KOBIL_SCT n
    kernel_configure_variable USB_SERIAL_MCT_U232 n
    kernel_configure_variable USB_SERIAL_METRO n
    kernel_configure_variable USB_SERIAL_MOS7720 n
    kernel_configure_variable USB_SERIAL_MOS7840 n
    kernel_configure_variable USB_SERIAL_NAVMAN n
    kernel_configure_variable USB_SERIAL_PL2303 n
    kernel_configure_variable USB_SERIAL_OTI6858 n
    kernel_configure_variable USB_SERIAL_QCAUX n
    kernel_configure_variable USB_SERIAL_QUALCOMM n
    kernel_configure_variable USB_SERIAL_SPCP8X5 n
    kernel_configure_variable USB_SERIAL_SAFE n
    kernel_configure_variable USB_SERIAL_SIERRAWIRELESS n
    kernel_configure_variable USB_SERIAL_SYMBOL n
    kernel_configure_variable USB_SERIAL_TI n
    kernel_configure_variable USB_SERIAL_CYBERJACK n
    kernel_configure_variable USB_SERIAL_XIRCOM n
    kernel_configure_variable USB_SERIAL_OPTION n
    kernel_configure_variable USB_SERIAL_OMNINET n
    kernel_configure_variable USB_SERIAL_OPTICON n
    kernel_configure_variable USB_SERIAL_XSENS_MT n
    kernel_configure_variable USB_SERIAL_WISHBONE n
    kernel_configure_variable USB_SERIAL_SSU100 n
    kernel_configure_variable USB_SERIAL_QT2 n
    kernel_configure_variable USB_SERIAL_DEBUG n
    kernel_configure_variable USB_EMI62 n
    kernel_configure_variable USB_EMI26 n
    kernel_configure_variable USB_ADUTUX n
    kernel_configure_variable USB_SEVSEG n
    kernel_configure_variable USB_RIO500 n
    kernel_configure_variable USB_LEGOTOWER n
    kernel_configure_variable USB_LCD n
    kernel_configure_variable USB_CYPRESS_CY7C63 n
    kernel_configure_variable USB_CYTHERM n
    kernel_configure_variable USB_IDMOUSE n
    kernel_configure_variable USB_FTDI_ELAN n
    kernel_configure_variable USB_APPLEDISPLAY n
    kernel_configure_variable USB_LD n
    kernel_configure_variable USB_TRANCEVIBRATOR n
    kernel_configure_variable USB_IOWARRIOR n
    kernel_configure_variable USB_TEST n
    kernel_configure_variable USB_ISIGHTFW n
    kernel_configure_variable USB_YUREX n
    kernel_configure_variable USB_ATM n
    kernel_configure_variable USB_SPEEDTOUCH n
    kernel_configure_variable USB_CXACRU n
    kernel_configure_variable USB_UEAGLEATM n
    kernel_configure_variable USB_XUSBATM n
    kernel_configure_variable MMC_SPI n
    kernel_configure_variable LEDS_TRIGGER_TRANSIENT n
    kernel_configure_variable LEDS_TRIGGER_CAMERA n
    kernel_configure_variable RTC_DRV_ABX80X n
    kernel_configure_variable RTC_DRV_DS1307 n
    kernel_configure_variable RTC_DRV_DS1374 n
    kernel_configure_variable RTC_DRV_DS1672 n
    kernel_configure_variable RTC_DRV_MAX6900 n
    kernel_configure_variable RTC_DRV_RS5C372 n
    kernel_configure_variable RTC_DRV_ISL1208 n
    kernel_configure_variable RTC_DRV_ISL12022 n
    kernel_configure_variable RTC_DRV_X1205 n
    kernel_configure_variable RTC_DRV_PCF8523 n
    kernel_configure_variable RTC_DRV_PCF8563 n
    kernel_configure_variable RTC_DRV_PCF8583 n
    kernel_configure_variable RTC_DRV_M41T80 n
    kernel_configure_variable RTC_DRV_BQ32K n
    kernel_configure_variable RTC_DRV_S35390A n
    kernel_configure_variable RTC_DRV_FM3130 n
    kernel_configure_variable RTC_DRV_RX8581 n
    kernel_configure_variable RTC_DRV_RX8025 n
    kernel_configure_variable RTC_DRV_EM3027 n
    kernel_configure_variable RTC_DRV_M41T93 n
    kernel_configure_variable RTC_DRV_M41T94 n
    kernel_configure_variable RTC_DRV_DS1302 n
    kernel_configure_variable RTC_DRV_DS1305 n
    kernel_configure_variable RTC_DRV_DS1390 n
    kernel_configure_variable RTC_DRV_R9701 n
    kernel_configure_variable RTC_DRV_RX4581 n
    kernel_configure_variable RTC_DRV_RS5C348 n
    kernel_configure_variable RTC_DRV_MAX6902 n
    kernel_configure_variable RTC_DRV_PCF2123 n
    kernel_configure_variable RTC_DRV_DS3232 n
    kernel_configure_variable RTC_DRV_PCF2127 n
    kernel_configure_variable RTC_DRV_RV3029C2 n
    kernel_configure_variable UIO n
    kernel_configure_variable UIO_PDRV_GENIRQ n
    kernel_configure_variable PRISM2_USB n
    kernel_configure_variable R8712U n
    kernel_configure_variable R8188EU n
    kernel_configure_variable VT6656 n
    kernel_configure_variable SPEAKUP n
    kernel_configure_variable SPEAKUP_SYNTH_SOFT n
    kernel_configure_variable LIRC_IMON n
    kernel_configure_variable LIRC_RPI n
    kernel_configure_variable LIRC_SASEM n
    kernel_configure_variable LIRC_SERIAL n
    kernel_configure_variable FB_TFT n
    kernel_configure_variable FB_TFT_AGM1264K_FL n
    kernel_configure_variable FB_TFT_BD663474 n
    kernel_configure_variable FB_TFT_HX8340BN n
    kernel_configure_variable FB_TFT_HX8347D n
    kernel_configure_variable FB_TFT_HX8353D n
    kernel_configure_variable FB_TFT_HX8357D n
    kernel_configure_variable FB_TFT_ILI9163 n
    kernel_configure_variable FB_TFT_ILI9320 n
    kernel_configure_variable FB_TFT_ILI9325 n
    kernel_configure_variable FB_TFT_ILI9340 n
    kernel_configure_variable FB_TFT_ILI9341 n
    kernel_configure_variable FB_TFT_ILI9481 n
    kernel_configure_variable FB_TFT_ILI9486 n
    kernel_configure_variable FB_TFT_PCD8544 n
    kernel_configure_variable FB_TFT_RA8875 n
    kernel_configure_variable FB_TFT_S6D02A1 n
    kernel_configure_variable FB_TFT_S6D1121 n
    kernel_configure_variable FB_TFT_SSD1289 n
    kernel_configure_variable FB_TFT_SSD1306 n
    kernel_configure_variable FB_TFT_SSD1331 n
    kernel_configure_variable FB_TFT_SSD1351 n
    kernel_configure_variable FB_TFT_ST7735R n
    kernel_configure_variable FB_TFT_ST7789V n
    kernel_configure_variable FB_TFT_TINYLCD n
    kernel_configure_variable FB_TFT_TLS8204 n
    kernel_configure_variable FB_TFT_UC1701 n
    kernel_configure_variable FB_TFT_UPD161704 n
    kernel_configure_variable FB_TFT_WATTEROTT n
    kernel_configure_variable FB_FLEX n
    kernel_configure_variable FB_TFT_FBTFT_DEVICE n
    kernel_configure_variable EXTCON n
    kernel_configure_variable EXTCON_ARIZONA n
    kernel_configure_variable IIO n
    kernel_configure_variable IIO_BUFFER_CB n
    kernel_configure_variable MCP320X n
    kernel_configure_variable MCP3422 n
    kernel_configure_variable DHT11 n
    kernel_configure_variable HDC100X n
    kernel_configure_variable HTU21 n
    kernel_configure_variable INV_MPU6050_I2C n
    kernel_configure_variable TSL4531 n
    kernel_configure_variable VEML6070 n
    kernel_configure_variable BMP280 n
    kernel_configure_variable PWM_BCM2835 n
    kernel_configure_variable PWM_PCA9685 n
    kernel_configure_variable RPI_AXIPERF n
    kernel_configure_variable REISERFS_FS n
    kernel_configure_variable JFS_FS n
    kernel_configure_variable XFS_FS n
    kernel_configure_variable GFS2_FS n
    kernel_configure_variable OCFS2_FS n
    kernel_configure_variable BTRFS_FS n
    kernel_configure_variable NILFS2_FS n
    kernel_configure_variable QFMT_V1 n
    kernel_configure_variable QFMT_V2 n
    kernel_configure_variable FUSE_FS n
    kernel_configure_variable CUSE n
    kernel_configure_variable ISO9660_FS n
    kernel_configure_variable UDF_FS n
    kernel_configure_variable NTFS_FS n
    kernel_configure_variable ECRYPT_FS n
    kernel_configure_variable HFS_FS n
    kernel_configure_variable HFSPLUS_FS n
    kernel_configure_variable JFFS2_FS n
    kernel_configure_variable UBIFS_FS n
    kernel_configure_variable SQUASHFS n
    kernel_configure_variable NFSD n
    kernel_configure_variable CIFS n
    kernel_configure_variable 9P_FS n
    kernel_configure_variable NLS_CODEPAGE_737 n
    kernel_configure_variable NLS_CODEPAGE_775 n
    kernel_configure_variable NLS_CODEPAGE_850 n
    kernel_configure_variable NLS_CODEPAGE_852 n
    kernel_configure_variable NLS_CODEPAGE_855 n
    kernel_configure_variable NLS_CODEPAGE_857 n
    kernel_configure_variable NLS_CODEPAGE_860 n
    kernel_configure_variable NLS_CODEPAGE_861 n
    kernel_configure_variable NLS_CODEPAGE_862 n
    kernel_configure_variable NLS_CODEPAGE_863 n
    kernel_configure_variable NLS_CODEPAGE_864 n
    kernel_configure_variable NLS_CODEPAGE_865 n
    kernel_configure_variable NLS_CODEPAGE_866 n
    kernel_configure_variable NLS_CODEPAGE_869 n
    kernel_configure_variable NLS_CODEPAGE_936 n
    kernel_configure_variable NLS_CODEPAGE_950 n
    kernel_configure_variable NLS_CODEPAGE_932 n
    kernel_configure_variable NLS_CODEPAGE_949 n
    kernel_configure_variable NLS_CODEPAGE_874 n
    kernel_configure_variable NLS_ISO8859_8 n
    kernel_configure_variable NLS_CODEPAGE_1250 n
    kernel_configure_variable NLS_CODEPAGE_1251 n
    kernel_configure_variable NLS_ISO8859_1 n
    kernel_configure_variable NLS_ISO8859_2 n
    kernel_configure_variable NLS_ISO8859_3 n
    kernel_configure_variable NLS_ISO8859_4 n
    kernel_configure_variable NLS_ISO8859_5 n
    kernel_configure_variable NLS_ISO8859_6 n
    kernel_configure_variable NLS_ISO8859_7 n
    kernel_configure_variable NLS_ISO8859_9 n
    kernel_configure_variable NLS_ISO8859_13 n
    kernel_configure_variable NLS_ISO8859_14 n
    kernel_configure_variable NLS_ISO8859_15 n
    kernel_configure_variable NLS_KOI8_R n
    kernel_configure_variable NLS_KOI8_U n
    kernel_configure_variable DLM n
    kernel_configure_variable CRYPTO_USER n
    kernel_configure_variable CRYPTO_CTS n
    kernel_configure_variable CRYPTO_XTS n
    kernel_configure_variable CRYPTO_XCBC n
    kernel_configure_variable CRYPTO_TGR192 n
    kernel_configure_variable CRYPTO_WP512 n
    kernel_configure_variable CRYPTO_CAST5 n
    kernel_configure_variable CRYPTO_LZ4 n
}

INSANE_SKIP_${PN} = "installed-vs-shipped"
